// CredentialProviderTest.idl: CredentialProviderTest 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(CredentialProviderTest.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";
import "credentialprovider.idl";

cpp_quote("namespace glasssix {")
cpp_quote("namespace hello {")
[
    object,
    uuid(51717537-e400-46ed-97ad-14f80a3e694a),
    pointer_default(unique)
]
interface ISampleProvider : IUnknown
{
};
[
    object,
    uuid(3aaf78d3-9229-4632-ae71-2eb1e6250ee8),
    pointer_default(unique)
]
interface ISampleCredential : IUnknown
{
    HRESULT Initialize([in] CREDENTIAL_PROVIDER_USAGE_SCENARIO scenario,
        [in] ICredentialProviderUser* user,
        [in] const CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR* descriptors);
};
[
    uuid(e03d8900-55b1-40b4-ab5b-909c429ed5f7),
    version(1.0),
]
library CredentialProviderTestLib
{
    importlib("stdole2.tlb");
    [
        uuid(194df9f5-0d5e-4d96-b71c-fb91f2b73225)
    ]
    coclass SampleProvider
    {
        [default] interface ISampleProvider;
    };
    [
        uuid(7c6ca508-fa0e-4126-a2c7-62e4c7e2d498)
    ]
    coclass SampleCredential
    {
        [default] interface ISampleCredential;
    };
};
cpp_quote("}}")

import "shobjidl.idl";
import "shobjidl.idl";
